name: checks
on: push
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github .
  pyright:
    needs: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.311 # Optional (change me!)
